import Foundation

/// Detects machine-generated files by their in-file marker, for `RiskBrief`.
///
/// Filename heuristics only catch generators whose output has a recognisable
/// name (`*.pb.go`, `go.sum`, `vendor/`). Most don't: `wire_gen.go`,
/// `zz_generated_deepcopy.go`, `queries.sql.go` (sqlc), `mock_store.go`
/// variants, `schema.graphql.ts`, OpenAPI clients — all ordinary-looking
/// names. What they *do* share is a header marker, because the ecosystems
/// standardised on one:
///
/// - Go's `go generate` convention is a line matching
///   `^// Code generated .* DO NOT EDIT\.$`, and gofmt/vet tooling relies on
///   it, so Go codegen essentially always emits it.
/// - `@generated` is the GitHub-linguist / Meta convention, used by prettier,
///   Relay, protobuf-ts, and most JS/TS codegen.
///
/// Reading a bounded prefix of each changed file is cheap next to the review
/// itself, and it is the difference between a 4,000-line generated diff
/// ranking first (because it is big and has no test) and ranking last.
enum GeneratedCodeScanner {
    /// Lowercased; matched against a lowercased header.
    static let markers = [
        "do not edit",
        "@generated",
        "code generated by",
        "autogenerated by",
        "auto-generated by",
        "automatically generated by",
    ]

    /// How much of each file's head to inspect. Generated markers are a
    /// header convention; a license block or Go build tags can precede them,
    /// but not by much. Bounded so a multi-megabyte generated file costs the
    /// same as a small one.
    static let headerByteLimit = 4_096

    /// Ceiling on files inspected per run. A PR touching more files than this
    /// is already past the point where per-file ranking helps.
    static let maxFilesScanned = 500

    /// Returns the subset of `paths` whose file head carries a generated
    /// marker. Missing or unreadable files are simply absent from the
    /// result — this signal is never load-bearing.
    ///
    /// Runs off the caller's actor: hundreds of small synchronous reads
    /// would otherwise stall the main thread mid-review.
    static func scan(paths: [String], in worktree: URL) async -> Set<String> {
        let candidates = Array(paths.prefix(maxFilesScanned))
        guard !candidates.isEmpty else { return [] }
        return await Task.detached(priority: .userInitiated) {
            var found: Set<String> = []
            for path in candidates {
                let url = worktree.appendingPathComponent(path)
                guard let header = readHeader(at: url) else { continue }
                if hasMarker(header) { found.insert(path) }
            }
            return found
        }.value
    }

    /// True when `header` contains any generated marker.
    static func hasMarker(_ header: String) -> Bool {
        let lower = header.lowercased()
        return markers.contains { lower.contains($0) }
    }

    /// First `headerByteLimit` bytes of a file as text, or nil.
    ///
    /// `FileHandle.read(upToCount:)` rather than `String(contentsOf:)`: the
    /// files most worth identifying here are the enormous ones, and reading
    /// them whole to look at line 3 defeats the purpose. Decoding is lossy
    /// (`decoding:as:` on possibly-truncated UTF-8) because we only ever
    /// substring-match ASCII markers.
    private static func readHeader(at url: URL) -> String? {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return nil }
        defer { try? handle.close() }
        guard let data = try? handle.read(upToCount: headerByteLimit), !data.isEmpty else {
            return nil
        }
        return String(decoding: data, as: UTF8.self)
    }
}
